#pragma once
#include <iostream>
#include <string>
#include <fstream>
#include <windows.h>
#include <conio.h>
#include "variables.h"
#include "systemFunctions.h"
#include "bootAnimation.h"
#include "userFunctions.h"
#include "debugConsole.h"

int systemFunctions::bootLogo() {
	char t = (char)219; //localy defined variables so I dont have to type (char)219 every FUCKING TIME
	char s = ' ';//same as above
	cout << "\n\n\n\n\n\n\n";
	cout << "\t\t\t" << t << t << t << t << t << t << t << t << t << t << t << t << "     "; cout << t << t << t << t << t << t << t << t << s << s << s << "      "; cout << t << t << t << t << t << t << t << t << t << t << t << t << t << "      "; cout << t << t << t << "     "; cout << t << t << s << s << s << s << s << s << s << s << t << t << "     "; cout << s << s << s << s << t << t << s << s << s << s << "     "; cout << t << t << t << t << t << t << t << t << s << s << s << s << s << "     "; cout << t << t << t << t << t << t << t << t << s << s << s << "     " << endl;
	cout << "\t\t\t" << s << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << t << t << s << s << "      "; cout << s << s << s << s << s << s << t << t << s << s << s << s << s << "      "; cout << t << t << t << "     "; cout << t << t << s << s << s << s << s << s << s << s << t << t << "     "; cout << s << s << t << t << s << s << t << t << s << s << "     "; cout << t << t << s << s << s << s << s << t << t << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << t << t << s << s << "     " << endl;
	cout << "\t\t\t" << s << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << s << t << t << s << "      "; cout << s << s << s << s << s << s << t << t << s << s << s << s << s << "      "; cout << t << t << t << "     "; cout << t << t << s << s << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << s << t << t << s << s << s << "     "; cout << t << t << s << s << s << s << s << s << t << t << s << "     " << endl;
	cout << "\t\t\t" << s << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << s << t << t << s << "      "; cout << s << s << s << s << s << s << t << t << s << s << s << s << s << "      "; cout << t << t << t << "     "; cout << t << t << s << s << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << s << t << t << s << s << s << "     "; cout << t << t << s << s << s << s << s << s << s << t << t << "     " << endl;
	cout << "\t\t\t" << s << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << t << t << s << s << "      "; cout << s << s << s << s << s << s << t << t << s << s << s << s << s << "      "; cout << t << t << t << "     "; cout << t << t << s << s << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << t << t << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << s << s << t << t << "     " << endl;
	cout << "\t\t\t" << s << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << t << t << t << t << t << t << s << s << s << "      "; cout << s << s << s << s << s << s << t << t << s << s << s << s << s << "      "; cout << t << t << t << "     "; cout << t << t << t << t << t << t << t << t << t << t << t << t << "     "; cout << t << t << s << t << t << t << t << s << t << t << "     "; cout << t << t << t << t << t << t << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << s << s << t << t << "     " << endl;
	cout << "\t\t\t" << s << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << t << t << s << s << s << s << s << "      "; cout << s << s << s << s << s << s << t << t << s << s << s << s << s << "      "; cout << t << t << t << "     "; cout << t << t << s << s << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << t << t << s << s << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << s << t << t << s << "     " << endl;
	cout << "\t\t\t" << s << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << s << t << t << s << s << s << s << "      "; cout << s << s << s << s << s << s << t << t << s << s << s << s << s << "      "; cout << t << t << t << "     "; cout << t << t << s << s << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << t << t << s << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << t << t << s << s << "     " << endl;
	cout << "\t\t\t" << s << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << t << t << s << s << s << "      "; cout << s << s << s << s << s << s << t << t << s << s << s << s << s << "      "; cout << t << t << t << "     "; cout << t << t << s << s << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << t << t << s << s << s << "     " << endl;
	cout << "\t\t\t" << s << s << s << s << s << t << t << s << s << s << s << s << "     "; cout << t << t << s << s << s << s << s << t << t << s << s << "      "; cout << t << t << t << t << t << t << t << t << t << t << t << t << t << "      "; cout << t << t << t << "     "; cout << t << t << s << s << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << s << t << t << "     "; cout << t << t << s << s << s << s << s << t << t << s << s << s << s << "     "; cout << t << t << t << t << t << t << t << s << s << s << s << "     " << endl;
	return 0;
}
